### ISSUE TITLE
Power draw

### ISSUE THREAD

**Issue by probonopd** [Luzifer/lorabattery#1]
Cool project 👍 
How much power does this setup draw and how does this affect battery charge lifetime?

**Comment by Luzifer** [comment]
![image](https://user-images.githubusercontent.com/20142/90447762-41d70f80-e0e4-11ea-9f89-5c5cfd029b00.png)

It's quite hard to tell as I don't have proper measurements without measuring devices attached. My car currently has a 54Ah battery and while I needed to charge the battery every ~30d with the Chinese module attached I haven't charged it for way more than a month now (the graph above only shows ~30d because of a change in my metrics collection and a data-loss due to that).

The graph above shows the reported voltage filtered by `voltage < 13V` (above 13V is charging voltage and doesn't really show anything about the battery). The only charge the battery got were short drives with ~1.5km each. So no big drive which gave a proper charge.

Of course the short drives are impacting the discharge but in the end even without moving much the battery stays at around 11.9V so at around 40%… (Have to say that battery might not be fully okay as another device - which I don't use anymore - managed to discharge it down to a point where even the remote controlled locks didn't work anymore.)

**Comment by probonopd** [comment]
Thanks for your detailed explanation, really appreciate it. Keep it up! :+1:
